// lib/productImages.ts

export const productImagesMap: Record<string, string[]> = {
  "Kanjivaram Silk Pattu Dress": [
    "https://res.cloudinary.com/doux0jv3b/image/upload/1.2_frh2th.webp",
    "https://res.cloudinary.com/doux0jv3b/image/upload/1.1_xe6elm.webp",
    "https://res.cloudinary.com/doux0jv3b/image/upload/1.3_wry5kr.webp",
    "https://res.cloudinary.com/doux0jv3b/image/upload/1.5_hwzcqn.webp",
    "https://res.cloudinary.com/doux0jv3b/image/upload/1.4_ew0wwg.webp"
  ],
  "Royal Red Pattu Pavadai": [],
  "Pink Silk Pattu Frock": [],
  "Magenta Zari Pattu Dress": [],
  "Golden Pattu Silk Frock": [],
  "Emerald Green Pattu Dress": [],
  "Maroon Silk Pattu Pavadai": [],
  "Orange Brocade Pattu Dress": [],
  "Purple Kanchipuram Pattu": [],
  "Peacock Blue Pattu Frock": [],
  "Cream & Gold Pattu Dress": [],
  "Ruby Red Silk Pattu": [],
  "Diwali Special Gold Kurta Set": [],
  "Navratri Green Chaniya Choli": [],
  "Pongal Special Silk Dress": [],
  "Onam White & Gold Set": [],
  "Rakhi Special Pink Anarkali": [],
  "Ganesh Chaturthi Yellow Dress": [],
  "Makar Sankranti Orange Pavadai": [],
  "Ugadi Special Purple Set": [],
  "Holi Festive Rainbow Lehenga": [],
  "Vishu Golden Kasavu Set": [],
  "Royal Blue Lehenga Choli": [],
  "Pink Floral Lehenga Set": [],
  "Red Bridal Mini Lehenga": [],
  "Turquoise Silk Lehenga": [],
  "Lavender Net Lehenga Set": [],
  "Mustard Yellow Lehenga": [],
  "Wine Velvet Lehenga Set": [],
  "Peach Brocade Lehenga": [],
  "Classic Red Cotton Frock": [],
  "Green Silk Traditional Frock": [],
  "Blue Printed Ethnic Frock": [],
  "Yellow Chanderi Frock": [],
  "Coral Embroidered Frock": [],
  "Mint Green Angrakha Frock": [],
  "Burgundy Silk Frock": [],
  "Teal Bandhani Print Frock": [],
  "Sparkle Gold Party Dress": [],
  "Silver Sequin Gown": [],
  "Rose Pink Party Frock": [],
  "Navy Blue Velvet Dress": [],
  "Champagne Tulle Gown": [],
  "Black & Gold Party Dress": [],
  "Spring Blossom Silk Dress": [],
  "Summer Breeze Cotton Set": [],
  "Monsoon Magic Silk Frock": [],
  "Festive Fusion Crop Top Set": [],
  "Heritage Weave Pavadai": [],
  "Blossom Garden Anarkali": [],
};